# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\mysql\BookStore\Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(392, 222)
        Login.setStyleSheet("background url:{qrc:/Tencent_downloads/pictures/apex_eling.jpg}")
        self.frame = QtWidgets.QFrame(Login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 391, 221))
        self.frame.setStyleSheet("\n"
"\n"
"\n"
"QFrame{\n"
"background-color: rgb(121, 121, 121);\n"
"border-radius:20px  ;\n"
"}\n"
"QLineEdit{\n"
"border-radius:6px  ;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(242, 255, 210);\n"
"background-color: rgb(255, 170, 255);\n"
"font: 290 9pt \"Microsoft YaHei UI\";    \n"
"border-radius:3px  ;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txtUserName = QtWidgets.QLineEdit(self.frame)
        self.txtUserName.setGeometry(QtCore.QRect(261, 69, 106, 17))
        self.txtUserName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtUserName.setObjectName("txtUserName")
        self.txtPassword = QtWidgets.QLineEdit(self.frame)
        self.txtPassword.setGeometry(QtCore.QRect(261, 110, 106, 17))
        self.txtPassword.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.label_username = QtWidgets.QLabel(self.frame)
        self.label_username.setGeometry(QtCore.QRect(190, 70, 53, 15))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        self.label_username.setFont(font)
        self.label_username.setObjectName("label_username")
        self.label_password = QtWidgets.QLabel(self.frame)
        self.label_password.setGeometry(QtCore.QRect(190, 110, 53, 15))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(13)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_image = QtWidgets.QLabel(self.frame)
        self.label_image.setGeometry(QtCore.QRect(0, 30, 191, 171))
        self.label_image.setStyleSheet("image: url(:/new/prefix1/boy);\n"
"background-image: url(:/images/登录.png);")
        self.label_image.setText("")
        self.label_image.setObjectName("label_image")
        self.btnSignin = QtWidgets.QPushButton(self.frame)
        self.btnSignin.setGeometry(QtCore.QRect(320, 150, 51, 23))
        self.btnSignin.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"font: 290 9pt \"Microsoft YaHei UI\";")
        self.btnSignin.setObjectName("btnSignin")
        self.btnLogin = QtWidgets.QPushButton(self.frame)
        self.btnLogin.setGeometry(QtCore.QRect(260, 150, 51, 23))
        self.btnLogin.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(85, 85, 127);\n"
"background-color: rgb(255, 170, 255);\n"
"font: 290 9pt \"Microsoft YaHei UI\";\n"
"QPushButton::hover{background-color: rgb(32,137,230);\n"
"font: 290 9pt \"Microsoft YaHei UI\"; }")
        self.btnLogin.setObjectName("btnLogin")
        self.label_welcome = QtWidgets.QLabel(self.frame)
        self.label_welcome.setGeometry(QtCore.QRect(80, 20, 321, 20))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_welcome.setFont(font)
        self.label_welcome.setTextFormat(QtCore.Qt.RichText)
        self.label_welcome.setObjectName("label_welcome")
        self.LogincheckBox = QtWidgets.QCheckBox(self.frame)
        self.LogincheckBox.setGeometry(QtCore.QRect(350, 110, 16, 16))
        self.LogincheckBox.setText("")
        self.LogincheckBox.setObjectName("LogincheckBox")
        self.btnLogin_2 = QtWidgets.QPushButton(self.frame)
        self.btnLogin_2.setGeometry(QtCore.QRect(260, 180, 111, 23))
        self.btnLogin_2.setStyleSheet("background-color: rgb(255, 170, 255);\n"
"background-color: rgb(255, 170, 255);\n"
"font: 290 9pt \"Microsoft YaHei UI\";\n"
"QPushButton::hover{background-color: rgb(32,137,230);\n"
"font: 290 9pt \"Microsoft YaHei UI\"; }")
        self.btnLogin_2.setObjectName("btnLogin_2")
        self.label_image.raise_()
        self.txtUserName.raise_()
        self.txtPassword.raise_()
        self.label_username.raise_()
        self.label_password.raise_()
        self.btnSignin.raise_()
        self.btnLogin.raise_()
        self.label_welcome.raise_()
        self.LogincheckBox.raise_()
        self.btnLogin_2.raise_()

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.txtUserName, self.txtPassword)
        Login.setTabOrder(self.txtPassword, self.btnLogin)
        Login.setTabOrder(self.btnLogin, self.btnSignin)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "登录界面"))
        self.txtUserName.setPlaceholderText(_translate("Login", "请输入用户名"))
        self.txtPassword.setPlaceholderText(_translate("Login", "请输入密码"))
        self.label_username.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">用户名：</span></p></body></html>"))
        self.label_password.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">密  码：</span></p></body></html>"))
        self.btnSignin.setText(_translate("Login", "注册"))
        self.btnLogin.setText(_translate("Login", "登录"))
        self.label_welcome.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">欢迎使用我们的书店管理系统</span></p></body></html>"))
        self.btnLogin_2.setText(_translate("Login", "找回密码"))
import sources_rc
