# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\mysql\BookStore\forget_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forget_widget(object):
    def setupUi(self, forget_widget):
        forget_widget.setObjectName("forget_widget")
        forget_widget.resize(220, 260)
        forget_widget.setStyleSheet("QPushButton#confirm_pushButton\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_normal.png)0 0 0 0 strecth strecth\n"
"}\n"
"QPushButton#confirm_pushButton:hover\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_hover.png)0 0 0 0 strecth strecth\n"
"}\n"
"QPushButton#confirm_pushButton:pressed\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_down.png)0 0 0 0 strecth strecth\n"
"}\n"
"QPushButton#cancel_pushButton\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_normal.png)0 0 0 0 strecth strecth\n"
"}\n"
"QPushButton#cancel_pushButton:hover\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_hover.png)0 0 0 0 strecth strecth\n"
"}\n"
"QPushButton#cancel_pushButton:pressed\n"
"{\n"
"    border-image:url(:/pic/pic/button_login_down.png)0 0 0 0 strecth strecth\n"
"}")
        self.frame = QtWidgets.QFrame(forget_widget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 221, 261))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(121, 121, 121);\n"
"border-radius:20px  ;\n"
"}\n"
"QLineEdit{\n"
"border-radius:6px  ;\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(242, 255, 210);\n"
"background-color: rgb(255, 170, 255);\n"
"font: 290 9pt \"Microsoft YaHei UI\";    \n"
"border-radius:3px  ;\n"
"}")
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.acc_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.acc_lineEdit.setObjectName("acc_lineEdit")
        self.horizontalLayout.addWidget(self.acc_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.email_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.horizontalLayout_2.addWidget(self.email_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pass_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.pass_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass_lineEdit.setObjectName("pass_lineEdit")
        self.horizontalLayout_3.addWidget(self.pass_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pass2_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.pass2_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pass2_lineEdit.setObjectName("pass2_lineEdit")
        self.horizontalLayout_4.addWidget(self.pass2_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.confirm_pushButton = QtWidgets.QPushButton(self.frame)
        self.confirm_pushButton.setObjectName("confirm_pushButton")
        self.horizontalLayout_5.addWidget(self.confirm_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(self.frame)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout_5.addWidget(self.cancel_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        self.retranslateUi(forget_widget)
        QtCore.QMetaObject.connectSlotsByName(forget_widget)

    def retranslateUi(self, forget_widget):
        _translate = QtCore.QCoreApplication.translate
        forget_widget.setWindowTitle(_translate("forget_widget", "Form"))
        self.acc_lineEdit.setPlaceholderText(_translate("forget_widget", "账号"))
        self.email_lineEdit.setPlaceholderText(_translate("forget_widget", "联系方式"))
        self.pass_lineEdit.setPlaceholderText(_translate("forget_widget", "新密码"))
        self.pass2_lineEdit.setPlaceholderText(_translate("forget_widget", "确认密码"))
        self.confirm_pushButton.setText(_translate("forget_widget", "确认"))
        self.cancel_pushButton.setText(_translate("forget_widget", "取消"))
