# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\code\mysql\BookStore\fluent_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1187, 718)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 10, 1152, 648))
        self.frame.setStyleSheet("/*??*/\n"
"QWidget\n"
"{\n"
"color: rgb(50,76,108);  /*????*/\n"
"background-color: rgb(206,220,237); /*???*/\n"
"\n"
"}\n"
"QWidget#Contents\n"
"{\n"
"    color: rgb(50,76,108);  /*????*/\n"
"    background-color: rgb(206,220,237); /*???*/\n"
"}\n"
"/*??????*/\n"
"QPushButton#btnLogin,#btnLogout,#btnHide,#btnUpdate,#btnSure,#btnAdd,#btnDel\n"
"{\n"
"    background-color:rgba(189,209,233);/*???*/\n"
"    min-height:30px; /*????*/\n"
"    min-width:180px; /*????*/\n"
"    border-style:solid;/*???? solid?? none??? inset/outset 3D??*/\n"
"    border-width:4px; /*??????*/\n"
"    border-radius:10px;/*????????*/\n"
"    border-color:rgba(127,154,184);/*????*/\n"
"    font-size:12pt;/*?? ????*/\n"
"    color: rgb(50,76,108);/*????*/\n"
"    padding:6px; /*??*/\n"
"}\n"
"/*??????*/\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgba(192,240,255);/*???*/\n"
"    border-color:rgba(127,154,184);/*????*/\n"
"    border-style:solid;/*???? solid?? none??? inset/outset 3D??*/\n"
"    color: rgb(50,76,108);/*????*/\n"
"}\n"
"/*??????*/\n"
"QPushButton#btnLogin:hover,#btnLogout:hover,#btnHide:hover,#btnUpdate:hover,#btnSure:hover,#btnAdd:hover,#btnDel:hover\n"
"{\n"
"    background-color:rgba(192,221,244);/*???*/\n"
"    border-color:rgba(127,154,184);/*????*/\n"
"    color: rgb(50,76,108);/*????*/\n"
"}\n"
"QLineEdit\n"
"{\n"
"    background-color:rgb(206,220,237);/*???*/\n"
"    min-height:30px; /*????*/\n"
"    min-width:180px; /*????*/\n"
"    border-style:solid;/*???? solid?? none??? inset/outset 3D??*/\n"
"    border-width:4px; /*??????*/\n"
"    border-radius:10px;/*????????*/\n"
"    border-color:rgba(127,154,184);/*????*/\n"
"    font-size:12pt;/*?? ????*/\n"
"    color: rgb(50,76,108);/*????*/\n"
"    padding:6px;/*??*/\n"
"}\n"
"QCheckBox\n"
"{\n"
"    color:rgb(50,76,108);/*????*/\n"
"    background-color:rgb(206,220,237);/*???*/\n"
"}\n"
"QComboBox\n"
"{\n"
"    background-color:rgb(206,220,237);\n"
"    color:rgb(50,76,108);/*????*/\n"
"    border-style:solid;/*???? solid?? none??? inset/outset 3D??*/\n"
"    border-width:4px;/*??????*/\n"
"    border-radius:10px;/*????????*/\n"
"    border-color:rgba(127,154,184);/*????*/\n"
"    min-height:35px; /*????*/\n"
"    font-size:12pt;\n"
"}\n"
"/*??????????*/\n"
"QComboBox::drop-down\n"
"{\n"
"     width:20px;\n"
"     border:none;\n"
"     background:transparent;\n"
" }\n"
"/*????????*/\n"
"QComboBox::down-arrow\n"
"{\n"
"    image:url(:/image/array_down.png);\n"
"}\n"
"/*??????????*/\n"
"QComboBox QAbstractItemView\n"
"{\n"
" background-color: rgb(206,220,237); /*???*/\n"
"    color: rgb(50,76,108);/*????*/\n"
"outline:none;\n"
"}\n"
"/*??????item*/\n"
"QComboBox QAbstractItemView::item\n"
"{\n"
"    height:30px;\n"
"    color:rgb(50,76,108);/*????*/\n"
"}\n"
"/*???item??*/\n"
"QComboBox QAbstractItemView::item:selected\n"
"{\n"
"    background-color:rgb(206,220,237); /*???*/\n"
"    color:rgb(50,76,108);/*????*/\n"
"}\n"
"QLabel\n"
"{\n"
"    color:rgb(50,76,108);/*????*/\n"
"font-size:12pt;\n"
"border:none;/*????*/\n"
"}\n"
"QTabWidget\n"
"{\n"
"    background-color: rgb(206,220,237); /*???*/\n"
"    color:rgb(50,76,108);/*????*/\n"
"}\n"
"QTabBar::tab\n"
"{\n"
"    background-color:rgb(206,220,237); /*???*/\n"
"    color:rgb(50,76,108);/*????*/\n"
"    font-size:12pt;/*????*/\n"
"    height:30px; /*??*/\n"
"    min-width:100px;/*??*/\n"
"    border-top-left-radius:4px;/*??????????*/\n"
"    border-top-right-radius:4px;/*??????????*/\n"
"    margin-right: 5px;/*???  ????*/\n"
"    padding-left:5px;/*???--????*/\n"
"    padding-right:5px;/*???--????*/\n"
"}\n"
"QTabBar::tab:hover\n"
"{\n"
"    background-color: rgb(206,220,237); /*???*/\n"
"}\n"
"QTabBar::tab:selected\n"
"{\n"
"    background-color: rgb(189,209,233); /*???*/\n"
"}\n"
"QTableView,QTableWidget{\n"
"    background-color:rgb(206,220,237); /*???*/\n"
"    color:rgb(50,76,108);/*????*/\n"
"    selection-background-color:rgba(192,221,244);/*???*/;/*??????*/\n"
"    border:1px solid #E0DDDC;/*???1?????*/\n"
"    gridline-color:lightgray;/*????????????????*/\n"
"    font:bold 12pt;/*?? ????*/\n"
"}\n"
"/*??????*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(206,220,237); /*???*/\n"
"    border:0px solid #E0DDDC;/*????????0??????????*/\n"
"    border-bottom:1px solid #E0DDDC;/*??????????????????????Table?????????2px?????*/\n"
"    min-height:30px;;/*????*/\n"
"    font-size:12pt;/*????*/\n"
"}\n"
"QTreeWidget,QTreeView\n"
"{\n"
"    background-color:rgb(206,220,237); /*???*/\n"
"    color:rgb(50,76,108);/*????*/\n"
"    selection-background-color:rgba(5,23,200);/*??????*/\n"
"    font-size:12pt;/*????*/\n"
"}\n"
"/*????*/\n"
"QTreeWidget::branch:has-children:!has-siblings:closed,\n"
"QTreeWidget::branch:closed:has-children:has-siblings {\n"
"    border-image: none;\n"
"    image: url(:/image/add-line_horizontal.png);\n"
"}\n"
"/*????*/\n"
"QTreeWidget::branch:open:has-children:!has-siblings,\n"
"QTreeWidget::branch:open:has-children:has-siblings  {\n"
"    border-image: none;\n"
"    image: url(:/image/array_down.png);\n"
"}\n"
"/*????*/\n"
"QTreeView::branch:has-children:!has-siblings:closed,\n"
"QTreeView::branch:closed:has-children:has-siblings {\n"
"    border-image: none;\n"
"    image: url(:/image/add-line_horizontal.png);\n"
"}\n"
"/*????*/\n"
"QTreeView::branch:open:has-children:!has-siblings,\n"
"QTreeView::branch:open:has-children:has-siblings  {\n"
"    border-image: none;\n"
"    image: url(:/image/array_down.png);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_Close = QtWidgets.QPushButton(self.frame)
        self.btn_Close.setEnabled(True)
        self.btn_Close.setGeometry(QtCore.QRect(1110, 10, 20, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Close.sizePolicy().hasHeightForWidth())
        self.btn_Close.setSizePolicy(sizePolicy)
        self.btn_Close.setMinimumSize(QtCore.QSize(20, 20))
        self.btn_Close.setMaximumSize(QtCore.QSize(20, 20))
        self.btn_Close.setStyleSheet("QPushButton\n"
"{\n"
"background:#FF6694;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:#FF0000;\n"
"}\n"
"\n"
"")
        self.btn_Close.setText("")
        self.btn_Close.setObjectName("btn_Close")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 40, 137, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"\n"
"background-color:transparent;\n"
"\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"color: rgb(170, 255, 255);\n"
"}")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"\n"
"\n"
"border-radius:15px;\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"\n"
"\n"
"border-radius:15px;\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setStyleSheet("QLabel\n"
"{\n"
"\n"
"\n"
"border-radius:15px;\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"\n"
"\n"
"border-radius:15px;\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setStyleSheet("QLabel\n"
"{\n"
"\n"
"border-radius:15px;\n"
"color: rgb(255, 170, 255);\n"
"}\n"
"QLabel::hover{\n"
"    color: rgb(170, 255, 255);\n"
"}")
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.tableWidget_Admin = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_Admin.setGeometry(QtCore.QRect(220, 50, 771, 351))
        self.tableWidget_Admin.setObjectName("tableWidget_Admin")
        self.tableWidget_Admin.setColumnCount(0)
        self.tableWidget_Admin.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1187, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">管理员界面</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">会员界面</span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">职工界面</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">图书界面</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">购书记录</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt;\">退书记录</span></p></body></html>"))
import sources_rc
